### PR TITLE
Replace REAMDE documentation with link to PostMan Docs

### PR DESCRIPTION
**Pull request by ZacharyKhan**
Replaces the long, tedious README documentation with a well-formatted PostMan Docs set up. Developers can access all endpoints via PostMan to see how they work with the click of a single button.

### CODE REVIEW

**Comment by RikkiGibson** [comment]
Thank you for your contribution. I can see how the Postman interface will help people learn to use this. I'd prefer to have it as a supplement rather than a replacement, mainly because I don't want to point to something I don't have control over as the sole source of API documentation.

I've definitely struggled to strike the balance between telling people the service behaviors and why it does things the way it does, and overwhelming people with detail when they're just trying to figure out how to use the thing in the beginning.

If you could bring the original documentation back into a .md file in the local repo, optionally improving the quality by migrating it to a separate file linked from README.md, maybe with a table of contents to improve navigation and some editing to improve clarity and push down the less important parts, I'd be happy to merge this PR.

**Comment by jschneidereit** [comment]
First, let's not conflate the words thorough and tedious.

Second, there is something to be said about keeping the documentation in lock-step with the implementation (a source controlled README). Furthermore, sample urls are currently provided, so I'm not sure how developers can't see how they work. 

Finally, replacing a detailed README with a single url that the owner does not have a way to prevent the eventuality of it disappearing seems ill advised. 

Perhaps the addition of your link to the top of the README instead of a full on replacement?

**Review by jschneidereit — CHANGES_REQUESTED** [review]
See discussion

**Comment by ZacharyKhan** [comment]
@RikkiGibson I'll do my best to figure out the .md stuff and submit a commit to this PR. 

@jschneidereit I thought it was not only more elegant and more efficient to use PostMan, but it would make the README short and to the point for this simple API. 

I have no issue sending you the PostMan collection and you can host it on your account. I pay for it so I figure I would give you the benefit of my already-paid-for account.

**Comment by ZacharyKhan** [comment]
I've updated the PR to include the link to the postman docs at the top of the API section in the README

**Review by RikkiGibson — APPROVED** [review]

**Comment by RikkiGibson** [comment]
Thanks again for providing the Postman docs!

**Pull request merged**
