### PR TITLE
Add lat/lng to FavoriteStopViewModel

### PR DESCRIPTION
**Pull request by RikkiGibson**
Addresses #16.
@ZacharyKhan you can play around with this now using https://corvallisbus.azurewebsites.net. 

Sample URL for your convenience:
https://corvallisbus.azurewebsites.net/api/favorites?stops=11776,10308&location=44.5645659,-123.2620435

Will be changing corvallisb.us to point here soon. Probably on Sunday just so that if I mess up nobody's inconvenienced.

### CODE REVIEW

**Comment by ZacharyKhan** [comment]
@RikkiGibson Great, I’ll update the PostMan Docs to point to the new api url and submit a PR.

**Comment by RikkiGibson** [comment]
I think I was unclear-- https://corvallisb.us is still gonna be the main location long term, I'm just holding off deploying to it because there are some details to work out to move from my current host to Azure.

**Comment by RikkiGibson** [comment]
New version is live on corvallisb.us now 👍

**Comment by ZacharyKhan** [comment]
Oh perfect!

**Pull request merged**
